### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by AdrianaY** [IES-Jaume-Balmes/2020-21-DAW2-M12-Andromeda#36]
usuarios (si es que aún no esta terminada).
música (tabla por hacer aún).

**Comment by dgarcia19jaume** [comment]
Tablas y sus relaciones creadas, solo falta lista_detalle

**Comment by AdrianaY** [comment]
Base de datos migrada de h2-console a phpmyadmin.

**Comment by dgarcia19jaume** [comment]
BD terminada.
